export interface VerbConjugation {
  infinitive: string
  pastSimple: string
  pastParticiple: string
  presentParticiple: string
  gerund: string
  thirdPersonSingular: string
  presentContinuous: string
  simplePresent: string
}

export interface Verb {
  id: string
  infinitive: string
  translation: string
  category: string
  conjugation: VerbConjugation
}

export const verbs: Verb[] = [
  {
    id: "be",
    infinitive: "be",
    translation: "ser/estar",
    category: "irregular",
    conjugation: {
      infinitive: "be",
      pastSimple: "was/were",
      pastParticiple: "been",
      presentParticiple: "being",
      gerund: "being",
      thirdPersonSingular: "is",
      presentContinuous: "am/is/are being",
      simplePresent: "am/is/are",
    },
  },
  {
    id: "become",
    infinitive: "become",
    translation: "tornar-se",
    category: "irregular",
    conjugation: {
      infinitive: "become",
      pastSimple: "became",
      pastParticiple: "become",
      presentParticiple: "becoming",
      gerund: "becoming",
      thirdPersonSingular: "becomes",
      presentContinuous: "am/is/are becoming",
      simplePresent: "becomes",
    },
  },
  {
    id: "begin",
    infinitive: "begin",
    translation: "começar",
    category: "irregular",
    conjugation: {
      infinitive: "begin",
      pastSimple: "began",
      pastParticiple: "begun",
      presentParticiple: "beginning",
      gerund: "beginning",
      thirdPersonSingular: "begins",
      presentContinuous: "am/is/are beginning",
      simplePresent: "begins",
    },
  },
  {
    id: "bend",
    infinitive: "bend",
    translation: "dobrar",
    category: "irregular",
    conjugation: {
      infinitive: "bend",
      pastSimple: "bent",
      pastParticiple: "bent",
      presentParticiple: "bending",
      gerund: "bending",
      thirdPersonSingular: "bends",
      presentContinuous: "am/is/are bending",
      simplePresent: "bends",
    },
  },
  {
    id: "bet",
    infinitive: "bet",
    translation: "apostar",
    category: "irregular",
    conjugation: {
      infinitive: "bet",
      pastSimple: "bet",
      pastParticiple: "bet",
      presentParticiple: "betting",
      gerund: "betting",
      thirdPersonSingular: "bets",
      presentContinuous: "am/is/are betting",
      simplePresent: "bets",
    },
  },
  {
    id: "bite",
    infinitive: "bite",
    translation: "morder",
    category: "irregular",
    conjugation: {
      infinitive: "bite",
      pastSimple: "bit",
      pastParticiple: "bitten",
      presentParticiple: "biting",
      gerund: "biting",
      thirdPersonSingular: "bites",
      presentContinuous: "am/is/are biting",
      simplePresent: "bites",
    },
  },
  {
    id: "bleed",
    infinitive: "bleed",
    translation: "sangrar",
    category: "irregular",
    conjugation: {
      infinitive: "bleed",
      pastSimple: "bled",
      pastParticiple: "bled",
      presentParticiple: "bleeding",
      gerund: "bleeding",
      thirdPersonSingular: "bleeds",
      presentContinuous: "am/is/are bleeding",
      simplePresent: "bleeds",
    },
  },
  {
    id: "blow",
    infinitive: "blow",
    translation: "soprar",
    category: "irregular",
    conjugation: {
      infinitive: "blow",
      pastSimple: "blew",
      pastParticiple: "blown",
      presentParticiple: "blowing",
      gerund: "blowing",
      thirdPersonSingular: "blows",
      presentContinuous: "am/is/are blowing",
      simplePresent: "blows",
    },
  },
  {
    id: "break",
    infinitive: "break",
    translation: "quebrar",
    category: "irregular",
    conjugation: {
      infinitive: "break",
      pastSimple: "broke",
      pastParticiple: "broken",
      presentParticiple: "breaking",
      gerund: "breaking",
      thirdPersonSingular: "breaks",
      presentContinuous: "am/is/are breaking",
      simplePresent: "breaks",
    },
  },
  {
    id: "bring",
    infinitive: "bring",
    translation: "trazer",
    category: "irregular",
    conjugation: {
      infinitive: "bring",
      pastSimple: "brought",
      pastParticiple: "brought",
      presentParticiple: "bringing",
      gerund: "bringing",
      thirdPersonSingular: "brings",
      presentContinuous: "am/is/are bringing",
      simplePresent: "brings",
    },
  },
  {
    id: "build",
    infinitive: "build",
    translation: "construir",
    category: "irregular",
    conjugation: {
      infinitive: "build",
      pastSimple: "built",
      pastParticiple: "built",
      presentParticiple: "building",
      gerund: "building",
      thirdPersonSingular: "builds",
      presentContinuous: "am/is/are building",
      simplePresent: "builds",
    },
  },
  {
    id: "buy",
    infinitive: "buy",
    translation: "comprar",
    category: "irregular",
    conjugation: {
      infinitive: "buy",
      pastSimple: "bought",
      pastParticiple: "bought",
      presentParticiple: "buying",
      gerund: "buying",
      thirdPersonSingular: "buys",
      presentContinuous: "am/is/are buying",
      simplePresent: "buys",
    },
  },
  {
    id: "catch",
    infinitive: "catch",
    translation: "pegar/capturar",
    category: "irregular",
    conjugation: {
      infinitive: "catch",
      pastSimple: "caught",
      pastParticiple: "caught",
      presentParticiple: "catching",
      gerund: "catching",
      thirdPersonSingular: "catches",
      presentContinuous: "am/is/are catching",
      simplePresent: "catches",
    },
  },
  {
    id: "choose",
    infinitive: "choose",
    translation: "escolher",
    category: "irregular",
    conjugation: {
      infinitive: "choose",
      pastSimple: "chose",
      pastParticiple: "chosen",
      presentParticiple: "choosing",
      gerund: "choosing",
      thirdPersonSingular: "chooses",
      presentContinuous: "am/is/are choosing",
      simplePresent: "chooses",
    },
  },
  {
    id: "come",
    infinitive: "come",
    translation: "vir",
    category: "irregular",
    conjugation: {
      infinitive: "come",
      pastSimple: "came",
      pastParticiple: "come",
      presentParticiple: "coming",
      gerund: "coming",
      thirdPersonSingular: "comes",
      presentContinuous: "am/is/are coming",
      simplePresent: "comes",
    },
  },
  {
    id: "cost",
    infinitive: "cost",
    translation: "custar",
    category: "irregular",
    conjugation: {
      infinitive: "cost",
      pastSimple: "cost",
      pastParticiple: "cost",
      presentParticiple: "costing",
      gerund: "costing",
      thirdPersonSingular: "costs",
      presentContinuous: "am/is/are costing",
      simplePresent: "costs",
    },
  },
  {
    id: "cut",
    infinitive: "cut",
    translation: "cortar",
    category: "irregular",
    conjugation: {
      infinitive: "cut",
      pastSimple: "cut",
      pastParticiple: "cut",
      presentParticiple: "cutting",
      gerund: "cutting",
      thirdPersonSingular: "cuts",
      presentContinuous: "am/is/are cutting",
      simplePresent: "cuts",
    },
  },
  {
    id: "deal",
    infinitive: "deal",
    translation: "lidar/negociar",
    category: "irregular",
    conjugation: {
      infinitive: "deal",
      pastSimple: "dealt",
      pastParticiple: "dealt",
      presentParticiple: "dealing",
      gerund: "dealing",
      thirdPersonSingular: "deals",
      presentContinuous: "am/is/are dealing",
      simplePresent: "deals",
    },
  },
  {
    id: "dig",
    infinitive: "dig",
    translation: "cavar",
    category: "irregular",
    conjugation: {
      infinitive: "dig",
      pastSimple: "dug",
      pastParticiple: "dug",
      presentParticiple: "digging",
      gerund: "digging",
      thirdPersonSingular: "digs",
      presentContinuous: "am/is/are digging",
      simplePresent: "digs",
    },
  },
  {
    id: "do",
    infinitive: "do",
    translation: "fazer",
    category: "irregular",
    conjugation: {
      infinitive: "do",
      pastSimple: "did",
      pastParticiple: "done",
      presentParticiple: "doing",
      gerund: "doing",
      thirdPersonSingular: "does",
      presentContinuous: "am/is/are doing",
      simplePresent: "does",
    },
  },
  {
    id: "draw",
    infinitive: "draw",
    translation: "desenhar",
    category: "irregular",
    conjugation: {
      infinitive: "draw",
      pastSimple: "drew",
      pastParticiple: "drawn",
      presentParticiple: "drawing",
      gerund: "drawing",
      thirdPersonSingular: "draws",
      presentContinuous: "am/is/are drawing",
      simplePresent: "draws",
    },
  },
  {
    id: "drink",
    infinitive: "drink",
    translation: "beber",
    category: "irregular",
    conjugation: {
      infinitive: "drink",
      pastSimple: "drank",
      pastParticiple: "drunk",
      presentParticiple: "drinking",
      gerund: "drinking",
      thirdPersonSingular: "drinks",
      presentContinuous: "am/is/are drinking",
      simplePresent: "drinks",
    },
  },
  {
    id: "drive",
    infinitive: "drive",
    translation: "dirigir",
    category: "irregular",
    conjugation: {
      infinitive: "drive",
      pastSimple: "drove",
      pastParticiple: "driven",
      presentParticiple: "driving",
      gerund: "driving",
      thirdPersonSingular: "drives",
      presentContinuous: "am/is/are driving",
      simplePresent: "drives",
    },
  },
  {
    id: "eat",
    infinitive: "eat",
    translation: "comer",
    category: "irregular",
    conjugation: {
      infinitive: "eat",
      pastSimple: "ate",
      pastParticiple: "eaten",
      presentParticiple: "eating",
      gerund: "eating",
      thirdPersonSingular: "eats",
      presentContinuous: "am/is/are eating",
      simplePresent: "eats",
    },
  },
  {
    id: "fall",
    infinitive: "fall",
    translation: "cair",
    category: "irregular",
    conjugation: {
      infinitive: "fall",
      pastSimple: "fell",
      pastParticiple: "fallen",
      presentParticiple: "falling",
      gerund: "falling",
      thirdPersonSingular: "falls",
      presentContinuous: "am/is/are falling",
      simplePresent: "falls",
    },
  },
  // Novos verbos adicionados da imagem
  {
    id: "feed",
    infinitive: "feed",
    translation: "alimentar",
    category: "irregular",
    conjugation: {
      infinitive: "feed",
      pastSimple: "fed",
      pastParticiple: "fed",
      presentParticiple: "feeding",
      gerund: "feeding",
      thirdPersonSingular: "feeds",
      presentContinuous: "am/is/are feeding",
      simplePresent: "feeds",
    },
  },
  {
    id: "feel",
    infinitive: "feel",
    translation: "sentir",
    category: "irregular",
    conjugation: {
      infinitive: "feel",
      pastSimple: "felt",
      pastParticiple: "felt",
      presentParticiple: "feeling",
      gerund: "feeling",
      thirdPersonSingular: "feels",
      presentContinuous: "am/is/are feeling",
      simplePresent: "feels",
    },
  },
  {
    id: "fight",
    infinitive: "fight",
    translation: "lutar",
    category: "irregular",
    conjugation: {
      infinitive: "fight",
      pastSimple: "fought",
      pastParticiple: "fought",
      presentParticiple: "fighting",
      gerund: "fighting",
      thirdPersonSingular: "fights",
      presentContinuous: "am/is/are fighting",
      simplePresent: "fights",
    },
  },
  {
    id: "find",
    infinitive: "find",
    translation: "encontrar",
    category: "irregular",
    conjugation: {
      infinitive: "find",
      pastSimple: "found",
      pastParticiple: "found",
      presentParticiple: "finding",
      gerund: "finding",
      thirdPersonSingular: "finds",
      presentContinuous: "am/is/are finding",
      simplePresent: "finds",
    },
  },
  {
    id: "fly",
    infinitive: "fly",
    translation: "voar",
    category: "irregular",
    conjugation: {
      infinitive: "fly",
      pastSimple: "flew",
      pastParticiple: "flown",
      presentParticiple: "flying",
      gerund: "flying",
      thirdPersonSingular: "flies",
      presentContinuous: "am/is/are flying",
      simplePresent: "flies",
    },
  },
  {
    id: "forget",
    infinitive: "forget",
    translation: "esquecer",
    category: "irregular",
    conjugation: {
      infinitive: "forget",
      pastSimple: "forgot",
      pastParticiple: "forgotten",
      presentParticiple: "forgetting",
      gerund: "forgetting",
      thirdPersonSingular: "forgets",
      presentContinuous: "am/is/are forgetting",
      simplePresent: "forgets",
    },
  },
  {
    id: "forgive",
    infinitive: "forgive",
    translation: "perdoar",
    category: "irregular",
    conjugation: {
      infinitive: "forgive",
      pastSimple: "forgave",
      pastParticiple: "forgiven",
      presentParticiple: "forgiving",
      gerund: "forgiving",
      thirdPersonSingular: "forgives",
      presentContinuous: "am/is/are forgiving",
      simplePresent: "forgives",
    },
  },
  {
    id: "freeze",
    infinitive: "freeze",
    translation: "congelar",
    category: "irregular",
    conjugation: {
      infinitive: "freeze",
      pastSimple: "froze",
      pastParticiple: "frozen",
      presentParticiple: "freezing",
      gerund: "freezing",
      thirdPersonSingular: "freezes",
      presentContinuous: "am/is/are freezing",
      simplePresent: "freezes",
    },
  },
  {
    id: "get",
    infinitive: "get",
    translation: "obter/conseguir",
    category: "irregular",
    conjugation: {
      infinitive: "get",
      pastSimple: "got",
      pastParticiple: "gotten",
      presentParticiple: "getting",
      gerund: "getting",
      thirdPersonSingular: "gets",
      presentContinuous: "am/is/are getting",
      simplePresent: "gets",
    },
  },
  {
    id: "give",
    infinitive: "give",
    translation: "dar",
    category: "irregular",
    conjugation: {
      infinitive: "give",
      pastSimple: "gave",
      pastParticiple: "given",
      presentParticiple: "giving",
      gerund: "giving",
      thirdPersonSingular: "gives",
      presentContinuous: "am/is/are giving",
      simplePresent: "gives",
    },
  },
  {
    id: "go",
    infinitive: "go",
    translation: "ir",
    category: "irregular",
    conjugation: {
      infinitive: "go",
      pastSimple: "went",
      pastParticiple: "gone",
      presentParticiple: "going",
      gerund: "going",
      thirdPersonSingular: "goes",
      presentContinuous: "am/is/are going",
      simplePresent: "goes",
    },
  },
  {
    id: "grow",
    infinitive: "grow",
    translation: "crescer",
    category: "irregular",
    conjugation: {
      infinitive: "grow",
      pastSimple: "grew",
      pastParticiple: "grown",
      presentParticiple: "growing",
      gerund: "growing",
      thirdPersonSingular: "grows",
      presentContinuous: "am/is/are growing",
      simplePresent: "grows",
    },
  },
  {
    id: "hang",
    infinitive: "hang",
    translation: "pendurar",
    category: "irregular",
    conjugation: {
      infinitive: "hang",
      pastSimple: "hung",
      pastParticiple: "hung",
      presentParticiple: "hanging",
      gerund: "hanging",
      thirdPersonSingular: "hangs",
      presentContinuous: "am/is/are hanging",
      simplePresent: "hangs",
    },
  },
  {
    id: "have",
    infinitive: "have",
    translation: "ter",
    category: "irregular",
    conjugation: {
      infinitive: "have",
      pastSimple: "had",
      pastParticiple: "had",
      presentParticiple: "having",
      gerund: "having",
      thirdPersonSingular: "has",
      presentContinuous: "am/is/are having",
      simplePresent: "has",
    },
  },
  {
    id: "hear",
    infinitive: "hear",
    translation: "ouvir",
    category: "irregular",
    conjugation: {
      infinitive: "hear",
      pastSimple: "heard",
      pastParticiple: "heard",
      presentParticiple: "hearing",
      gerund: "hearing",
      thirdPersonSingular: "hears",
      presentContinuous: "am/is/are hearing",
      simplePresent: "hears",
    },
  },
  {
    id: "hide",
    infinitive: "hide",
    translation: "esconder",
    category: "irregular",
    conjugation: {
      infinitive: "hide",
      pastSimple: "hid",
      pastParticiple: "hidden",
      presentParticiple: "hiding",
      gerund: "hiding",
      thirdPersonSingular: "hides",
      presentContinuous: "am/is/are hiding",
      simplePresent: "hides",
    },
  },
  {
    id: "hit",
    infinitive: "hit",
    translation: "bater",
    category: "irregular",
    conjugation: {
      infinitive: "hit",
      pastSimple: "hit",
      pastParticiple: "hit",
      presentParticiple: "hitting",
      gerund: "hitting",
      thirdPersonSingular: "hits",
      presentContinuous: "am/is/are hitting",
      simplePresent: "hits",
    },
  },
  {
    id: "hold",
    infinitive: "hold",
    translation: "segurar",
    category: "irregular",
    conjugation: {
      infinitive: "hold",
      pastSimple: "held",
      pastParticiple: "held",
      presentParticiple: "holding",
      gerund: "holding",
      thirdPersonSingular: "holds",
      presentContinuous: "am/is/are holding",
      simplePresent: "holds",
    },
  },
  {
    id: "hurt",
    infinitive: "hurt",
    translation: "machucar",
    category: "irregular",
    conjugation: {
      infinitive: "hurt",
      pastSimple: "hurt",
      pastParticiple: "hurt",
      presentParticiple: "hurting",
      gerund: "hurting",
      thirdPersonSingular: "hurts",
      presentContinuous: "am/is/are hurting",
      simplePresent: "hurts",
    },
  },
  {
    id: "keep",
    infinitive: "keep",
    translation: "manter",
    category: "irregular",
    conjugation: {
      infinitive: "keep",
      pastSimple: "kept",
      pastParticiple: "kept",
      presentParticiple: "keeping",
      gerund: "keeping",
      thirdPersonSingular: "keeps",
      presentContinuous: "am/is/are keeping",
      simplePresent: "keeps",
    },
  },
  {
    id: "know",
    infinitive: "know",
    translation: "saber/conhecer",
    category: "irregular",
    conjugation: {
      infinitive: "know",
      pastSimple: "knew",
      pastParticiple: "known",
      presentParticiple: "knowing",
      gerund: "knowing",
      thirdPersonSingular: "knows",
      presentContinuous: "am/is/are knowing",
      simplePresent: "knows",
    },
  },
  {
    id: "lead",
    infinitive: "lead",
    translation: "liderar",
    category: "irregular",
    conjugation: {
      infinitive: "lead",
      pastSimple: "led",
      pastParticiple: "led",
      presentParticiple: "leading",
      gerund: "leading",
      thirdPersonSingular: "leads",
      presentContinuous: "am/is/are leading",
      simplePresent: "leads",
    },
  },
  {
    id: "leave",
    infinitive: "leave",
    translation: "deixar/sair",
    category: "irregular",
    conjugation: {
      infinitive: "leave",
      pastSimple: "left",
      pastParticiple: "left",
      presentParticiple: "leaving",
      gerund: "leaving",
      thirdPersonSingular: "leaves",
      presentContinuous: "am/is/are leaving",
      simplePresent: "leaves",
    },
  },
  {
    id: "lend",
    infinitive: "lend",
    translation: "emprestar",
    category: "irregular",
    conjugation: {
      infinitive: "lend",
      pastSimple: "lent",
      pastParticiple: "lent",
      presentParticiple: "lending",
      gerund: "lending",
      thirdPersonSingular: "lends",
      presentContinuous: "am/is/are lending",
      simplePresent: "lends",
    },
  },
  {
    id: "let",
    infinitive: "let",
    translation: "deixar/permitir",
    category: "irregular",
    conjugation: {
      infinitive: "let",
      pastSimple: "let",
      pastParticiple: "let",
      presentParticiple: "letting",
      gerund: "letting",
      thirdPersonSingular: "lets",
      presentContinuous: "am/is/are letting",
      simplePresent: "lets",
    },
  },
]
